version: '3'

services:
  facebook:
    build: ./frontend
    container_name: facebook
    ports :
      - '3000:3000'
    stdin_open : true
    tty : true
  nginx:
    image: nginx
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - userservice
      - statusservice
      - storyservice
    links :
      - storyservice
      - statusservice
      - userservice
    

  userservice:
    build: ./user
    container_name: userservice
    restart: unless-stopped
    depends_on:
      - userdb

  statusservice:
    build: ./status
    container_name: statusservice
    restart: unless-stopped
    depends_on:
      - statusdb
      - userservice

  storyservice:
    container_name: storyservice
    build: ./story
    restart: unless-stopped
    depends_on:
      - storydb
      - storyobjectdb
      - userservice
   

  userdb:
    image: mongo:latest
    ports:
        - "5000:27017"
    container_name: userdb
    volumes: 
      - ./userdb:/docker-entrypoint-initdb.d
      - userdata:/data/db

  storydb:
    image: mongo:latest
    ports:
        - "5001:27017"
    container_name: storydb
    volumes: 
      - ./storydb:/docker-entrypoint-initdb.d
      - storydata:/data/db

  statusdb:
   image: mongo:latest
   ports:
        - "5002:27017"
   container_name: statusdb
   volumes: 
      - ./statusdb:/docker-entrypoint-initdb.d
      - statusdata:/data/db

  storyobjectdb:
    image: minio/minio:latest
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server --address 0.0.0.0:9000 /data
    volumes:
      - storyobjectdb:/data

volumes:
  userdata:
  statusdata:
  storydata:
  storyobjectdb: